### ISSUE TITLE
Getting error while install on official opscode "php" cookbook under OS X 10.8.5

### ISSUE THREAD

**Issue by josefglatz** [applicationsonline/librarian-chef#24] opened 2013-12-22 20:17 UTC
```
cookbook 'php',
    :git => 'git://github.com/opscode-cookbooks/php'
```

```
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/tsort.rb:153:in `tsort_each': topological sort failed: ["windows", "powershell"] (TSort::Cyclic)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/tsort.rb:184:in `each_strongly_connected_component'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/tsort.rb:211:in `each_strongly_connected_component_from'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/tsort.rb:220:in `each_strongly_connected_component_from'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/tsort.rb:210:in `each_strongly_connected_component_from'
    from /Library/Ruby/Gems/1.8/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in `each'
    from /Library/Ruby/Gems/1.8/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in `tsort_each_child'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/tsort.rb:204:in `each_strongly_connected_component_from'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/tsort.rb:183:in `each_strongly_connected_component'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/tsort.rb:181:in `tsort_each_node'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/tsort.rb:181:in `each_strongly_connected_component'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/tsort.rb:149:in `tsort_each'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/tsort.rb:136:in `tsort'
    from /Library/Ruby/Gems/1.8/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:31:in `sort'
    from /Library/Ruby/Gems/1.8/gems/librarian-0.1.1/lib/librarian/resolver.rb:73:in `sort'
    from /Library/Ruby/Gems/1.8/gems/librarian-0.1.1/lib/librarian/resolver.rb:19:in `resolve'
    from /Library/Ruby/Gems/1.8/gems/librarian-0.1.1/lib/librarian/action/resolve.rb:26:in `run'
    from /Library/Ruby/Gems/1.8/gems/librarian-0.1.1/lib/librarian/cli.rb:169:in `resolve!'
    from /Library/Ruby/Gems/1.8/gems/librarian-chef-0.0.2/lib/librarian/chef/cli.rb:41:in `install'
    from /Library/Ruby/Gems/1.8/gems/thor-0.18.1/lib/thor/command.rb:27:in `__send__'
    from /Library/Ruby/Gems/1.8/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /Library/Ruby/Gems/1.8/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /Library/Ruby/Gems/1.8/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /Library/Ruby/Gems/1.8/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from /Library/Ruby/Gems/1.8/gems/librarian-0.1.1/lib/librarian/cli.rb:26:in `bin!'
    from /Library/Ruby/Gems/1.8/gems/librarian-0.1.1/lib/librarian/cli.rb:31:in `returning_status'
    from /Library/Ruby/Gems/1.8/gems/librarian-0.1.1/lib/librarian/cli.rb:26:in `bin!'
    from /Library/Ruby/Gems/1.8/gems/librarian-0.1.1/lib/librarian/cli.rb:47:in `with_environment'
    from /Library/Ruby/Gems/1.8/gems/librarian-0.1.1/lib/librarian/cli.rb:26:in `bin!'
    from /Library/Ruby/Gems/1.8/gems/librarian-chef-0.0.2/bin/librarian-chef:7
    from /usr/bin/librarian-chef:23:in `load'
    from /usr/bin/librarian-chef:23
```

**Comment by yfeldblum** [comment] 2013-12-22 23:39
Closing this issue in favor of applicationsonline/librarian#159. The problem is cyclic dependencies, and the Librarian resolver does not detect them early enough.

**Closed as completed by yfeldblum** 2013-12-22 23:39 UTC
